/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import datos.MaestroDAO;
import dominio.Maestros;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jeff
 */
public class Mantenimiento_Maestros extends javax.swing.JInternalFrame {

    DefaultTableModel modelo1;

    /**
     * Creates new form Mantenimiento_Sedes
     */
    public Mantenimiento_Maestros() {
        initComponents();
        limpio.setVisible(false);
        modelo1 = new DefaultTableModel();   //ASIGNAMOS UN NUEVO DEFAULTABLEMODEL AL OBJETO MODELO1
        modelo1.addColumn("CODIGO");
        modelo1.addColumn("NOMBRE");
        modelo1.addColumn("DIRECCION");
        modelo1.addColumn("TELEFONO");
        modelo1.addColumn("EMAIL");
        modelo1.addColumn("ESTADO");
        tabla1.setModel(modelo1);
        String datos[] = new String[6];
        MaestroDAO dao = new MaestroDAO();
        List<Maestros> maestros = dao.select();
        for (Maestros maestro : maestros) {
            datos[0] = maestro.getCodigo();
            datos[1] = maestro.getNombre();
            datos[2] = maestro.getDireccion();
            datos[3] = maestro.getTelefono();
            datos[4] = maestro.getEmail();
            datos[5] = maestro.getEstatus();
            modelo1.addRow(datos);
            tabla1.setModel(modelo1);
        }
    }

    public void limpiar() {
        txt_codigo.setText("");
        txt_nombre.setText("");
        activo.setSelected(false);
        inactivo.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ESTADO = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        activo = new javax.swing.JRadioButton();
        inactivo = new javax.swing.JRadioButton();
        limpio = new javax.swing.JRadioButton();
        btn_buscar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(true);

        jLabel4.setText("CODIGO:");

        jLabel5.setText("NOMBRE:");

        jLabel6.setText("ESTATUS:");

        ESTADO.add(activo);
        activo.setText("ACTIVO");

        ESTADO.add(inactivo);
        inactivo.setText("INACTIVO");

        ESTADO.add(limpio);

        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_modificar.setText("MODIFICAR");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabla1);

        jLabel7.setText("TELEFONO:");

        jLabel8.setText("DIRECCION:");

        jLabel9.setText("EMAIL:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(activo)
                                .addGap(18, 18, 18)
                                .addComponent(inactivo)
                                .addGap(18, 18, 18)
                                .addComponent(limpio))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_direccion))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_nombre))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_telefono)
                                            .addComponent(txt_email))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar)
                    .addComponent(btn_guardar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modificar)
                    .addComponent(btn_eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(activo)
                        .addComponent(inactivo)
                        .addComponent(limpio)))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed

        MaestroDAO sedesDAO = new MaestroDAO();
        Maestros maestroConsultar = new Maestros();
        maestroConsultar.setCodigo(txt_codigo.getText());
        maestroConsultar = sedesDAO.query(maestroConsultar);
        txt_nombre.setText(maestroConsultar.getNombre());
        if ("1".equals(maestroConsultar.getEstatus())) {
            activo.setSelected(true);
        }
        if ("0".equals(maestroConsultar.getEstatus())) {
            inactivo.setSelected(true);
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed

        if (txt_codigo.getText().length() != 0 && txt_nombre.getText().length() != 0 && activo.isSelected() || inactivo.isSelected()) {
            MaestroDAO maestroDAO = new MaestroDAO();
            Maestros sedeInsertar = new Maestros();
            sedeInsertar.setCodigo(txt_codigo.getText());
            sedeInsertar.setNombre(txt_nombre.getText());
            sedeInsertar.setDireccion(txt_direccion.getText());
            sedeInsertar.setTelefono(txt_telefono.getText());
            sedeInsertar.setEmail(txt_email.getText());
            if (activo.isSelected()) {
                sedeInsertar.setEstatus("1");
            }
            if (inactivo.isSelected()) {
                sedeInsertar.setEstatus("0");
            }
            maestroDAO.insert(sedeInsertar);
            JOptionPane.showMessageDialog(null, "Modulo registrado correctamente");
        }

        /*-----------------------------------------------------------------------------------------------*/
        modelo1 = new DefaultTableModel();   //ASIGNAMOS UN NUEVO DEFAULTABLEMODEL AL OBJETO MODELO1
        modelo1.addColumn("CODIGO");
        modelo1.addColumn("NOMBRE");
        modelo1.addColumn("DIRECCION");
        modelo1.addColumn("TELEFONO");
        modelo1.addColumn("EMAIL");
        modelo1.addColumn("ESTADO");
        tabla1.setModel(modelo1);
        String datos[] = new String[6];
        MaestroDAO dao = new MaestroDAO();
        List<Maestros> maestros = dao.select();
        for (Maestros maestro : maestros) {
            datos[0] = maestro.getCodigo();
            datos[1] = maestro.getNombre();
            datos[2] = maestro.getDireccion();
            datos[3] = maestro.getTelefono();
            datos[4] = maestro.getEmail();
            datos[5] = maestro.getEstatus();
            modelo1.addRow(datos);
            tabla1.setModel(modelo1);
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        Maestros sedesEliminar = new Maestros();
        MaestroDAO sedesDAO = new MaestroDAO();
        sedesEliminar.setCodigo(txt_codigo.getText());
        sedesDAO.delete(sedesEliminar);
        JOptionPane.showMessageDialog(null, "Perfil Eliminado.");

        /*-----------------------------------------------------------------------------------------------*/
        modelo1 = new DefaultTableModel();   //ASIGNAMOS UN NUEVO DEFAULTABLEMODEL AL OBJETO MODELO1
        modelo1.addColumn("CODIGO");
        modelo1.addColumn("NOMBRE");
        modelo1.addColumn("DIRECCION");
        modelo1.addColumn("TELEFONO");
        modelo1.addColumn("EMAIL");
        modelo1.addColumn("ESTADO");
        tabla1.setModel(modelo1);
        String datos[] = new String[3];
        MaestroDAO dao = new MaestroDAO();
        List<Maestros> maestros = dao.select();
        for (Maestros maestro : maestros) {
            datos[0] = maestro.getCodigo();
            datos[1] = maestro.getNombre();
            datos[2] = maestro.getDireccion();
            datos[3] = maestro.getTelefono();
            datos[4] = maestro.getEmail();
            datos[5] = maestro.getEstatus();
            modelo1.addRow(datos);
            tabla1.setModel(modelo1);
        }
        limpiar();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        MaestroDAO sedesDAO = new MaestroDAO();
        Maestros sedeActualizar = new Maestros();
        sedeActualizar.setCodigo(txt_codigo.getText());
        sedeActualizar.setNombre(txt_nombre.getText());
        sedeActualizar.setDireccion(txt_direccion.getText());
        sedeActualizar.setTelefono(txt_telefono.getText());
        sedeActualizar.setEmail(txt_email.getText());
        if (activo.isSelected()) {
            sedeActualizar.setEstatus("1");
        }
        if (inactivo.isSelected()) {
            sedeActualizar.setEstatus("0");
        }
        sedesDAO.update(sedeActualizar);
        JOptionPane.showMessageDialog(null, "Modulo actualizado correctamente");

        /*-----------------------------------------------------------------------------------------------*/
        modelo1 = new DefaultTableModel();   //ASIGNAMOS UN NUEVO DEFAULTABLEMODEL AL OBJETO MODELO1
        modelo1.addColumn("CODIGO");
        modelo1.addColumn("NOMBRE");
        modelo1.addColumn("DIRECCION");
        modelo1.addColumn("TELEFONO");
        modelo1.addColumn("EMAIL");
        modelo1.addColumn("ESTADO");
        tabla1.setModel(modelo1);
        String datos[] = new String[6];
        MaestroDAO dao = new MaestroDAO();
        List<Maestros> maestros = dao.select();
        for (Maestros maestro : maestros) {
            datos[0] = maestro.getCodigo();
            datos[1] = maestro.getNombre();
            datos[2] = maestro.getDireccion();
            datos[3] = maestro.getTelefono();
            datos[4] = maestro.getEmail();
            datos[5] = maestro.getEstatus();
            modelo1.addRow(datos);
            tabla1.setModel(modelo1);
        }
        limpiar();
    }//GEN-LAST:event_btn_modificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ESTADO;
    private javax.swing.JRadioButton activo;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JRadioButton inactivo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton limpio;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
